[pytest]
# --headed: Add this option to open the browser window
# --browser: Default browser (other options: 'firefox' / 'webkit')
# -v: Enable verbose terminal output
addopts = --browser chromium -v --base-url=https://automationteststore.com --alluredir=allure-results

# Test files and functions locations
testpaths = tests
python_files = test_*.py
python_functions = test_*

# Default timeout
timeout = 30

# Custom test markers
markers =
    logged_in: Marks a test to run with an authenticated user

pythonpath = .
